baseURL: https://dapr.io/
languageCode: en-us
title: Dapr
theme: hugo-fresh
googleAnalytics: #Put in your tracking code without quotes like this: UA-XXXXXX...
#Disables warningss
disableKinds:
 -taxonomy
 -taxonomyTerm


params:
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: dapr
    # Hero subtitle (optional)
    subtitle: Event-driven, portable runtime for building microservice apps on cloud and edge.
    # Button text
    buttontext: Get started
    # Where the main hero button links to
    buttonlink: "#"
    # Hero image (from static/images/___)
    # image: illustrations/worker.svg
    # Footer logos (from static/images/logos/clients/___.svg)
    clientlogos:
    - systek
    - tribe
    - kromo
    - infinite
    - gutwork
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: Home
    url: /#
  - title: About
    url: /#about
  - title: Download
  - title: Docs
    url: /#docs
  - title: Community
    url: /#community
  # section1:
    # title: Great power comes
    # subtitle: with great responsibility
    # tiles:
    # - title: App builder
    #   icon: mouse-globe
    #   text: This is some explanatory text that is on two rows
    #   url: /
    #   buttonText: Free trial
    # - title: Cloud integration
    #   icon: laptop-cloud
    #   text: This is some explanatory text that is on two rows
    #   url: /
    #   buttonText: Get started
    # - title: Add-ons & plugins
    #   icon: plug-cloud
    #   text: This is some explanatory text that is on two rows
    #   url: /
    #   buttonText: Get started
  # section2:
    # title: You're here because you want the best
    # subtitle: And we know it
    # features:
    # - title: Powerful and unified interface
    #   text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
    #   # Icon (from /images/illustrations/icons/___.svg)
    #   icon: laptop-globe
    # - title: Cross-device synchronisation
    #   text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
    #   icon: doc-sync
    # - title: Nomad system
    #   text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
    #   icon: mobile-feed
  # section3:
    # title: One platform
    # subtitle: To rule them all
    # image: illustrations/mockups/app-mockup.png
    # buttonText: Get started
    # buttonLink: "#"
  # section4:
    # title: Our Clients love us!
    # subtitle: Lorem ipsum sit dolor amet is a dummy text used by typography industry
    # clients:
    # - name: Irma Walters
    #   quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
    #   job: Accountant
    #   img: 1
    # - name: John Bradley
    #   quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
    #   job: Financial Analyst
    #   img: 2
    # - name: Gary Blackman
    #   quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
    #   job: HR Manager
    #   img: 3
  # section5: true
  footer:
    # Logo (from /images/logos/___)
    # logo: fresh-white-alt.svg
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
    - link: https://github.com/dapr/dapr
      icon: github
    - link: https://twitter.com/DaprDev
      icon: twitter
    - link: /#
      icon: slack
    bulmalogo: false
